[package]
edition.workspace = true
license.workspace = true
name = "err"
version.workspace = true

[dependencies]
axum = { version = "0.6", default-features = false, features = ["json"] }
backtrace = "0.3"
serde_json = { version = "1.0" }
tracing = { version = "0.1" }
